// Auto-generated by convert_banks.py — do not edit
#pragma once
#include <string>

static const int GMO_NUM_BANKS = 43;

struct GmoBankInfo {
    const char* filename;  // stem, no extension
    const char* displayName;
    const char* category;
    int numWavetables;
    float speedMin;
    float speedMax;
    bool centerAtMax;  // if true, speedMax is at knob 50% (range doubles above)
};

static const GmoBankInfo GMO_BANKS[] = {
    {"GMO_ANIMALS", "Animals", "Other", 8, 0.01f, 3.0f, true},
    {"GMO_Acetone_Rhythm_King", "Acetone Rhythm King", "Drum Machines", 9, 0.5f, 5.0f, true},
    {"GMO_Artist_Series_Baseck_Dogs_And_Lasers", "Baseck: Dogs and Lasers", "Artist Series", 8, 0.01f, 3.0f, true},
    {"GMO_Artist_Series_Chad_Mossholder_808", "Chad Mossholder: 808", "Artist Series", 8, 0.01f, 3.0f, true},
    {"GMO_Artist_Series_Chad_Mossholder_EMI", "Chad Mossholder: EMI", "Artist Series", 8, 0.01f, 3.0f, true},
    {"GMO_Artist_Series_Chad_Mossholder_Monkeyballs", "Chad Mossholder: Monkeyballs", "Artist Series", 8, 0.01f, 3.0f, true},
    {"GMO_Artist_Series_Chad_Mossholder_SpeakNSpell", "Chad Mossholder: SpeakNSpell", "Artist Series", 8, 0.01f, 3.0f, true},
    {"GMO_Artist_Series_Chad_Mossholder_Static", "Chad Mossholder: Static", "Artist Series", 8, 0.01f, 3.0f, true},
    {"GMO_Artist_Series_Detroit_Underground_A", "Detroit Underground: A", "Artist Series", 13, 3.0f, 8.0f, true},
    {"GMO_Artist_Series_Detroit_Underground_B", "Detroit Underground: B", "Artist Series", 11, 3.0f, 8.0f, true},
    {"GMO_Artist_Series_Divkid", "Divkid", "Artist Series", 8, 0.01f, 7.0f, true},
    {"GMO_Artist_Series_Mario_Schambon", "Mario Schambon", "Artist Series", 8, 0.01f, 3.0f, true},
    {"GMO_Artist_Series_Rupert_Lally", "Rupert Lally", "Artist Series", 8, 0.01f, 3.0f, true},
    {"GMO_Artist_Series_Thomas_Fang", "Thomas Fang", "Artist Series", 9, 0.5f, 7.0f, true},
    {"GMO_Boss_DR_55", "Boss DR 55", "Drum Machines", 4, 1.0f, 10.0f, true},
    {"GMO_Casio_MT_500", "Casio MT 500", "Drum Machines", 10, 5.0f, 20.0f, true},
    {"GMO_Casio_RZ_1", "Casio RZ 1", "Drum Machines", 12, 1.0f, 20.0f, true},
    {"GMO_Casio_Sk_1", "Casio Sk 1", "Drum Machines", 6, 8.0f, 20.0f, true},
    {"GMO_Clocks", "Clocks", "Other", 9, 0.01f, 3.0f, true},
    {"GMO_Commodore_64", "Commodore 64", "Drum Machines", 6, 1.0f, 5.0f, true},
    {"GMO_Congas", "Congas", "Percussion", 12, 8.0f, 20.0f, true},
    {"GMO_Denon_CRB_90", "Denon CRB 90", "Drum Machines", 7, 1.0f, 10.0f, true},
    {"GMO_EMU_E_Drum", "EMU E Drum", "Drum Machines", 13, 5.0f, 20.0f, true},
    {"GMO_Eat_Static", "Eat Static", "Artist Series", 15, 0.5f, 7.0f, true},
    {"GMO_Farts", "Farts", "Other", 7, 0.5f, 3.0f, true},
    {"GMO_GLASS", "Glass", "Other", 8, 0.01f, 3.0f, true},
    {"GMO_Jazz_kit", "Jazz kit", "Percussion", 17, 2.0f, 5.0f, true},
    {"GMO_Kalimba", "Kalimba", "Other", 8, 0.01f, 3.0f, true},
    {"GMO_Korg_DDM_220", "Korg DDM 220", "Drum Machines", 8, 1.0f, 5.0f, true},
    {"GMO_Linn_LM_1", "Linn LM 1", "Drum Machines", 15, 3.0f, 7.0f, true},
    {"GMO_METAL", "Metal", "Other", 8, 0.01f, 5.0f, true},
    {"GMO_MOUTH_BANK_A", "Mouth Bank A", "Other", 8, 0.01f, 20.0f, true},
    {"GMO_MOUTH_BANK_B", "Mouth Bank B", "Other", 11, 0.01f, 10.0f, true},
    {"GMO_Marimba", "Marimba", "Other", 8, 1.0f, 5.0f, true},
    {"GMO_Roland_CR_78", "Roland CR 78", "Drum Machines", 8, 2.0f, 10.0f, true},
    {"GMO_SNARES", "Snares", "Percussion", 10, 0.01f, 20.0f, true},
    {"GMO_Sequential_Circuits_Drumtraks", "Sequential Circuits Drumtraks", "Drum Machines", 12, 2.0f, 10.0f, true},
    {"GMO_TABLA", "Tabla", "Percussion", 9, 0.01f, 5.0f, true},
    {"GMO_TABLABOLMOUTH", "Tabla Bols (mouth)", "Other", 7, 0.01f, 6.0f, true},
    {"GMO_TOM", "Tom", "Percussion", 8, 0.01f, 10.0f, true},
    {"GMO_Vermona_DRM_1", "Vermona DRM 1", "Drum Machines", 10, 10.0f, 20.0f, true},
    {"GMO_WOOD", "Wood", "Other", 8, 0.01f, 7.0f, true},
    {"GMO_kicks", "Kicks", "Percussion", 10, 0.25f, 3.0f, true},
};
