// Auto-generated by gen_1800_bins.py — do not edit
#pragma once

static const int BADIDEA1800_NUM_KITS = 24;

struct BadIdea1800KitInfo {
    const char* filename;
    const char* displayName;
    const char* sampleNames[12];
};

static const BadIdea1800KitInfo BADIDEA1800_KITS[] = {
    {"1800_AcetoneRhythmAce", "Acetone Rhythm Ace", {"Kick1", "Snare1", "Snare2", "Hhcl", "Hhop", "Clave", "Perc1", "Perc2", "Perc3", "Perc4", "Perc5", "Perc6"}},
    {"1800_AcetoneRhythmKing", "Acetone Rhythm King", {"Kick", "Snare", "Snare2", "Wood", "Wood2", "Bongo1", "Bongo2", "Bongo3", "Bongo4", "Hhc", "Hho", "Crash"}},
    {"1800_AkaiMPC2000", "Akai MPC2000", {"Kick", "Snare", "Snare2", "Clap", "Rim", "Rim2", "Hhc", "Hho", "Toml", "Tomm", "Tomh", "Tomfx"}},
    {"1800_AlesisHR16", "Alesis HR16", {"Kick", "Snare3", "Stick", "Clap", "Hhc", "Hho", "Congahi", "Congalo", "Cabasa", "Cowbell", "Agogo", "Tamb"}},
    {"1800_ArpAxxe", "Arp Axxe", {"Axxekick2", "Axxekick3", "Axxekick4", "Axxesn1", "Axxesn2", "Axxesn3", "Axxehc2", "Axxehc3", "Axxehhc1", "Axxehhc2", "Axxehho1", "Axxehho2"}},
    {"1800_CasioCZ230S", "Casio CZ230S", {"Czkick", "Czsnare", "Czclap", "Czrim", "Czchh", "Czohh", "Cztoml", "Cztomm", "Cztomh", "Czcow", "Czride", "Czcrash"}},
    {"1800_CasioRZ1", "Casio RZ1", {"Kirz", "Snrz", "Rsrz", "Hcrz", "Horz", "Clrz", "Tm1rz", "Tm2rz", "Tm3rz", "Ccrz", "Crrz", "Cbrz"}},
    {"1800_CheetahMD16", "Cheetah MD16", {"Kick", "Snare", "Clap", "Clap2", "Snap", "Zap", "Hhc", "Hho", "Toml", "Tomh", "Cowbelll", "Cowbellh"}},
    {"1800_DrBohmS78", "Dr. Bohm S78", {"S78bdrum", "S78snare", "S78chh", "S78ohh", "S78tom1", "S78tom2", "S78tom3", "S78clave", "S78shaker", "S78cow", "S78guiro1", "S78guiro2"}},
    {"1800_ElectroHarmonixDRM15", "Electro-Harmonix DRM15", {"Bd1", "Bd2", "Sd2", "Sdclp1", "Sdrim1", "Tom1", "Tom2", "Hh1", "Hh2", "Hh3", "Hh4", "Hh5"}},
    {"1800_EmuProteus3", "Emu Proteus 3", {"Snare1", "Snare2", "Stick", "Block", "Conga", "Perc1", "Perc2", "Snap", "Shaker", "Bell1", "Bell2", "Cowbell"}},
    {"1800_FrickeMFB712", "Fricke MFB712", {"Mfbbd1", "Mfbbd2", "Mfbsn", "Mfb1rim", "Mfb2rim", "Mfbbong", "Mfbhhc", "Mfbhhcl", "Mfbhhop", "Mfb1tom", "Mfb3tom", "Mfb4tom"}},
    {"1800_KawaiR50e", "Kawai R50e", {"R50bd3", "R50clap1", "R50clap2", "R50click", "R50snap", "R50rim", "R50elec", "R50hatc1", "R50hato1", "R50etoml", "R50etomm", "R50etomh"}},
    {"1800_KorgMinipops", "Korg Minipops", {"Bd1", "Bd2", "Bd3", "Sd1", "Sd2", "Sd3", "Sdfx", "Wood1", "Wood2", "Tom1", "Hihat1", "Hihat2"}},
    {"1800_LinnLM1", "Linn LM1", {"Lm1kick1", "Lm1sd1", "Lm1clap", "Lm1sst", "Lm1cabasa", "Lm1chh", "Lm1ohh", "Lm1hitom", "Lm1conga", "Lm1congal", "Lm1cowb", "Lm1tamb"}},
    {"1800_Roland606DR55", "Roland 606 + DR55", {"Kick", "Kickwa", "Snare", "Snarewa", "Rimwa", "Hatwa", "Hhc", "Hho", "Toml", "Tomm", "Tomh", "Cymbal"}},
    {"1800_Roland727", "Roland 727", {"Loconga", "Hmconga", "Hoconga", "Lobongo", "Hibongo", "Lotimba", "Hitimba", "Cabasa", "Maracas", "Quijada", "Whistel", "Whistle"}},
    {"1800_Roland808", "Roland 808", {"Kick", "Snare", "Rimshot", "Clap", "Hhclosed", "Hhopen", "Congamid", "Congahi", "Clave", "Maracas", "Cowbell", "Cymbal"}},
    {"1800_Roland909", "Roland 909", {"Kick", "Snareshort", "Snarelong", "Rimshot", "Clap", "Hhc", "Hho", "Toml", "Tomm", "Tomh", "Ride", "Crash"}},
    {"1800_RolandCR78", "Roland CR78", {"Kick", "Snare", "Rimshot", "Congal", "Bongol", "Bongoh", "Hh", "Hhm", "Guiro", "Tamb", "Cowbell", "Cymbal"}},
    {"1800_SequentialDrumtraks", "Sequential Drumtraks", {"Dtkick", "Dtsnare", "Dtclap", "Dtrimshot", "Dtcabasa", "Dtclosedhat", "Dtopenhat", "Dttom01", "Dttom02", "Dtcowbell", "Dttamborine", "Dtride"}},
    {"1800_SimmonsSDS100", "Simmons SDS100", {"Sdsk1", "Sdss1", "Sdss2", "Sdss3", "Sdss4", "Sdss5", "Sdss6", "Sdss7", "Sdss8", "Sdst1", "Sdst2", "Sdst3"}},
    {"1800_VermonaDRM1", "Vermona DRM1", {"Kick", "Kick2", "Snare", "Snare2", "Click", "Toml", "Tomh", "Hat", "Hat2", "Hat3", "Cabasashort", "Multi"}},
    {"1800_YamahaDD5", "Yamaha DD5", {"Ydd5kick", "Ydd5snare", "Ydd5clap", "Ydd5rim", "Ydd5hhcl", "Ydd5hhop", "Ydd5conga", "Ydd5tom3lo", "Ydd5tom2mi", "Ydd5tom1hi", "Ydd5cowbell", "Ydd5cym"}},
};
